### ISSUE TITLE
Issue while launching jnlp through iced tea 1.8.3

### ISSUE THREAD

**Issue by Yoshitha24** [AdoptOpenJDK/IcedTea-Web#735] opened 2021-01-05 07:16 UTC
We have moved to OpenJDK 8 and are integrating it with Adopt IcedTeaWeb 1.8.3. We are facing some problems while launching which is inconsistent. Sometimes during launch, "net.sourceforge.jnlp.LaunchException: Fatal: Launch Error: Could not launch JNLP file." error is seen and launching is terminated. Please see  [java console.txt](https://github.com/AdoptOpenJDK/IcedTea-Web/files/5768601/java.console.txt),  [java details.txt](https://github.com/AdoptOpenJDK/IcedTea-Web/files/5768603/java.details.txt) for the bug report. Please note that this error is not consistent and occurs randomly.
![BE1](https://user-images.githubusercontent.com/74032351/103616984-66c50580-4f53-11eb-890f-378d39979b8b.PNG)

 Sometimes we see that the GUI is launched but some features are not working. This is throwing a "java.lang.ClassNotFoundException". The following error is also seen on the console - "Failed to set com.jgoodies.plaf.plastic.PlasticLookAndFeel".  Please see [feature_fail.txt](https://github.com/AdoptOpenJDK/IcedTea-Web/files/5768607/feature_fail.txt)

We have tried many ways to resolve this but in vain. We read about cache issue in IcedTea and have even executed "_**javaws -Xclearcache**_" command before launching the jnlp files but that didn't work too. Additionally we are getting the below log in the console sometimes : " _Cannot clear the cache at this time. Try later. If the problem persists, try closing your browser(s) & JNLP applications. At the end you can try to kill all java applications.
You can clear cache by javaws -Xclearcache or via itw-settings Cache -> View files -> Purge_". 
We even tried icedtea built within AdoptOpenJDK 8 but that has the same issue.

Can you please suggest a solution?

**Comment by Jamila891** [comment] 2021-01-07 09:11
@Yoshitha24 this problem is not fixed in the IcedTeaWeb 1.8.x branch, but fixed in the master. You can try the master today by using OpenWebStart (https://github.com/karakun/OpenWebStart). Please give us feedback if the problem is solved there. Once this is done, we can check if a backport to 1.8.x is possible.

**Comment by Yoshitha24** [comment] 2021-01-19 10:52
Hi,

Thanks for the help. We are currently testing with OpenWebStart. We will update you on the results. Can I know the reason why this inconsistent behavior is seen in IcedTea?
Why is IcedTea sometimes not able to access the jars downloaded to the cache and throwing ClassNotFoundException which is resulting in some features not working properly? We have seen this situation in cases where multiple GUIs are launched and kept running in the same system. We have cross checked if any jar needed is not downloaded or tampered in the cache, but everything is in order. Many of the GUIs are running fine, but some in between are not functioning properly.

**Closed** 2021-05-27 12:52 UTC
