### ISSUE TITLE
Improve re-use of HTTP connections

### ISSUE THREAD

**Issue by sclassen** [AdoptOpenJDK/IcedTea-Web#709] opened 2020-10-02 21:08 UTC
This is a followup issue from https://github.com/karakun/OpenWebStart/issues/152.

A good starting point may be https://techblog.bozho.net/caveats-of-httpurlconnection/

**Comment by douph1** [comment] 2020-10-05 07:16
I'm not ok with this conclusion
>do not disconnect your connections after you read their response
You must call disconnect() so KeepAlive can reuse tcp connexion. It will not disconnect from the socket if the Http response support keep-alive and if the pool is not already full of idle connexion.
But you must absolutly be sure to have read all the inputStream and ErrorStream before disconnect to be assured that the connexion remain in the keep-alive pool

Maybe we can just find where we don't properly cleanup connexion stream to allow reuse before moving to another http client impl

**Comment by douph1** [comment] 2020-10-05 07:29
Just to justify :
https://docs.oracle.com/javase/8/docs/technotes/guides/net/http-keepalive.html
Section : What can you do to help with Keep-Alive?

And : Changes in JDK 6
>Now in JDK 6, the behavior is to read up to 512 Kbytes off the connection in a background thread, thus allowing the connection to be reused.

But relaying on this 512 read is not the best way. We must read all .. ourself

We do it in all our application with always all http-keepalive reuse.

**Comment by douph1** [comment] 2020-10-05 10:49
I deleted my previous answer because my new experience does not reproduce the same effect as previously.
I will consider closing the inputStream vs disconnect.
However, HttpUrlConnection connection reuse works great with Keep-Alive if all input and error streams are consumed.

**Closed** 2020-11-26 09:53 UTC

**Comment by douph1** [comment] 2020-11-26 11:28
@janakmulani can you give a reason when you close a issue ? did it was addressed on IcedTea-Web ? which branch ? wich PR ?

**Comment by janakmulani** [comment] 2020-11-26 11:40
@douph1  We reviewed your comment and concluded that you can no longer reproduce the issue (slow startup).  That is why we decided to close it. If you find that the issue is still occurring you can open it again. It will be helpful to provide us with a sample app that allows us to reproduce.

**Comment by douph1** [comment] 2020-11-26 12:05
I have no complaint about slow startup.
Better asking @sclassen what he would like to do with this issue.
My comment about my deleted comment is about the fact that swallowing all the inputStream+errorStream is sufficient to reuse http connection.
**If** ITW don't reuse the TCP connexion for other http connexion this must be because the two stream are not fully read.
I actually don't know if ITW suffer from bad http reuse connection but as @sclassen as created this issue he probably thinking of it.
So we can ask him a reproducible test case/sample or close it as "incomplete"
