### ISSUE TITLE
Issue about reconstitution Hashtable java

### ISSUE THREAD

**Issue by Tay08** [AdoptOpenJDK/IcedTea-Web#445] opened 2019-10-02 13:10 UTC
Context : 
Using AdoptOpenJDK 
openjdk version "1.8.0_212"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_212-b04)
OpenJDK Client VM (AdoptOpenJDK)(build 25.212-b04, mixed mode) include Iced Tea Web

Encountered problem : 
When i use the package on thick client application with Java Web Started, an error occured : 
```
Unable to read PrivilegeSet:
java.io.StreamCorruptedException
        at java.util.Hashtable.reconstitutionPut(Hashtable.java:1242)
        at java.util.Hashtable.readObject(Hashtable.java:1215)
        at sun.reflect.GeneratedMethodAccessor22.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1170)
        at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2178)
        at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2069)
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1573)
        at java.io.ObjectInputStream.readObject(ObjectInputStream.java:431)
        at wt.security.PrivilegeSet.read(PrivilegeSet.java:264)
        at wt.security.PrivilegeSet.<init>(PrivilegeSet.java:58)
        at wt.security.PrivilegeSet.<init>(PrivilegeSet.java:33)
        at wt.security.PrivilegeSet.newPrivilegeSet(PrivilegeSet.java:122)
        at wt.security.PrivilegeSet.newPrivilegeSet(PrivilegeSet.java:95)
        at wt.security.Access.<init>(Access.java:13)
        at wt.security.FileAccess.<init>(FileAccess.java:35)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at java.lang.Class.newInstance(Class.java:442)
        at wt.security.Access.getAccessImpl(Access.java:44)
        at wt.security.FileAccess.getFileAccess(FileAccess.java:49)
        at wt.security.FileAccess.getFileAccess(FileAccess.java:63)
        at wt.clients.util.http.HTTPUploadDownload.isAbsoluteDirectoryPath(HTTPUploadDownload.java:2523)
        at wt.clients.util.http.HTTPUploadDownload.isAbsoluteFilePath(HTTPUploadDownload.java:2512)
        at wt.clients.util.http.HTTPUploadDownload.validateFileWrite(HTTPUploadDownload.java:2209)
        at wt.clients.util.http.HTTPUploadDownload.validateDownloadEntries(HTTPUploadDownload.java:2181)
        at wt.clients.util.http.HTTPUploadDownload.performDownloadOperation(HTTPUploadDownload.java:1416)
        at wt.clients.util.http.HTTPUploadDownload.access$200(HTTPUploadDownload.java:55)
        at wt.clients.util.http.HTTPUploadDownload$HTTPUploadDownloadThread.run(HTTPUploadDownload.java:2731)
        at wt.clients.util.http.HTTPUploadDownload.performDownload(HTTPUploadDownload.java:1159)
        at com.airbus.mdm.jigs.tabs.contents.ContentsPanel$1.run(ContentsPanel.java:280)
```

**Comment by sclassen** [comment] 2019-10-02 13:25
I asume this is a closed source, so you cannot provide the JNLP and the jars for us to reproduce the error.
Can you at least post the code for the constructor and the code for the method `read()` of the class "PrivilegeSet".

**Comment by Tay08** [comment] 2019-10-02 14:14
Here is the constructor and the code for the method read() of the class "PrivilegeSet".
```
void read()
    {
        try
        {
            FileInputStream fileinputstream = new FileInputStream(privSetFile);
            ObjectInputStream objectinputstream = new ObjectInputStream(fileinputstream);
            synchronized(privileges)
            {
                privileges = (Hashtable)objectinputstream.readObject();
            }
            objectinputstream.close();
        }
        catch(FileNotFoundException filenotfoundexception)
        {
            privileges = new Hashtable();
        }
        catch(Exception exception)
        {
            System.out.println("Unable to read PrivilegeSet: ");
            exception.printStackTrace();
        }
    }
```

**Comment by sclassen** [comment] 2019-10-02 22:05
Ok, so it looks like the deserialization of the `privSetFile` fails. Reason for this is that 2 entries have the same hash. As I do not know what the content of the privSetFile is I can not really help much more.
Can you try to deserialize the content of the file in an application which is started without icedtea-web?
But it is very important, that the application uses the very same JVM as you are using with icedtea-web. I suspect the source of the problem to be an incompatibility between the JVM which has written the privSetFile and the JVM which you are now using to read it.

**Comment by hendrikebbers** [comment] 2019-11-11 07:44
@Tay08 can we close the issue?

**Closed** 2020-01-30 10:58 UTC
Labels: bug
