### ISSUE TITLE
AdoptOpenJDK: Issues in running sample jnlp files

### ISSUE THREAD

**Issue by JAIMY86** [AdoptOpenJDK/IcedTea-Web#347] opened 2019-08-01 10:55 UTC
[itw-javantx-2019-08-01_16_17_39.263.zip](https://github.com/AdoptOpenJDK/IcedTea-Web/files/3456291/itw-javantx-2019-08-01_16_17_39.263.zip)
[itw-javantx-2019-08-01_16_17_39.263.zip](https://github.com/AdoptOpenJDK/IcedTea-Web/files/3456294/itw-javantx-2019-08-01_16_17_39.263.zip)

Dear Team,
   Thanks for providing support.

We are looking to migrate from Oracle JRE to AdoptOpenJDK. But we have issues running JNLP files in our environment after installing  OpenJDK8U-jre_x64_windows_hotspot_8u222b10.msi where it snot running any sample JNLP files eg:(https://docs.oracle.com/javase/tutorialJWS/samples/uiswing/AccessibleScrollDemoProject/AccessibleScrollDemo.jnlp).

We tried many troubleshooting scenarios, but nothing worked out. Please find the attached log files.

Could you please support us.

**Comment by douph1** [comment] 2019-08-01 11:42
Hi,
>Unable to use Firefox's proxy settings. Using "DIRECT" as proxy type
+
>The host of https://docs.oracle.com/javase/tutorialJWS/samples/uiswing/AccessibleScrollDemoProject/AccessibleScrollDemo.jnlp file seems down, or you are simply offline.
>You are trying to get resource https://docs.oracle.com/javase/tutorialJWS/samples/uiswing/AccessibleScrollDemoProject/AccessibleScrollDemo.jnlp but it is not in cache and could not be downloaded. Attempting to continue, but you may expect failure

Maybe you must configure a proxy via itweb-settings.exe

**Comment by douph1** [comment] 2019-08-01 12:06
because you run it from IE 
C:\Users\obzbuxc\AppData\Local\Microsoft\Windows\ **INetCache\IE** \BNTD9VNR\AccessibleScrollDemo.jnlp
and IcedteaWeb don't know the IE proxy settings (only Firefox)

**Comment by JAIMY86** [comment] 2019-08-01 12:19
Hi ,

Thanks for the quick reply. But If we run standalone jnlp by downloading it and then running provides the same error.

Thanks,
Jaimy

sent from VMWare Boxer

On 01-Aug-2019 5:37 PM, Philippe Doussot <notifications@github.com> wrote:
Diese Nachricht enthielt potentiell unsichere
HTML Skripte. Diese wurden entfernt.
Die Nachricht kann nun gelesen, geoeffnet oder
bearbeitet werden.

===================================================

This message contained potentially unsafe HTML script
code that was removed.
Now you can safely view, open or edit this message.


because you run it from IE
C:\Users\obzbuxc\AppData\Local\Microsoft\Windows\ INetCache\IE \BNTD9VNR\AccessibleScrollDemo.jnlp
and IcedteaWeb don't know the IE proxy settings (only Firefox)

**Comment by VargheseJohnAllianz** [comment] 2019-08-01 13:37
> Hi,
> 
> Unable to use Firefox's proxy settings. Using "DIRECT" as proxy type
> 
> 
> 
> 
> 
> The host of https://docs.oracle.com/javase/tutorialJWS/samples/uiswing/AccessibleScrollDemoProject/AccessibleScrollDemo.jnlp file seems down, or you are simply offline.
> You are trying to get resource https://docs.oracle.com/javase/tutorialJWS/samples/uiswing/AccessibleScrollDemoProject/AccessibleScrollDemo.jnlp but it is not in cache and could not be downloaded. Attempting to continue, but you may expect failure
> 
> Maybe you must configure a proxy via itweb-settings.exe

Hi,
I am working along with Jaimy on this issue. We tried with manual Proxy Server & Automatic Proxy Configuration script, but no joy. No setting changed in the control panel other than enabling logging & Proxy setting.
Attaching error log files here.
Also tried to open the jnlp file from IE11 & also downloaded the file to C:\temp. Same behavior.
Path to jnlp tried : https://docs.oracle.com/javase/tutorialJWS/samples/uiswing/AccessibleScrollDemoProject/AccessibleScrollDemo.jnlp

Any pointers are most welcome. Somehow I feel that the proxy setting we provided is not applied and is reverting to DIRECT connection.

[JnlpLaunchErrorLogs_With_ProxyConfigScriptDefined.zip](https://github.com/AdoptOpenJDK/IcedTea-Web/files/3456957/JnlpLaunchErrorLogs_With_ProxyConfigScriptDefined.zip)
[JnlpLaunchErrorLogs_With_ProxyServerHardcoded.zip](https://github.com/AdoptOpenJDK/IcedTea-Web/files/3456958/JnlpLaunchErrorLogs_With_ProxyServerHardcoded.zip)

**Comment by VargheseJohnAllianz** [comment] 2019-08-01 14:04
> Hi,
> Unable to use Firefox's proxy settings. Using "DIRECT" as proxy type
> The host of https://docs.oracle.com/javase/tutorialJWS/samples/uiswing/AccessibleScrollDemoProject/AccessibleScrollDemo.jnlp file seems down, or you are simply offline.
> You are trying to get resource https://docs.oracle.com/javase/tutorialJWS/samples/uiswing/AccessibleScrollDemoProject/AccessibleScrollDemo.jnlp but it is not in cache and could not be downloaded. Attempting to continue, but you may expect failure
> Maybe you must configure a proxy via itweb-settings.exe
> 
> Hi,
> I am working along with Jaimy on this issue. We tried with manual Proxy Server & Automatic Proxy Configuration script, but no joy. No setting changed in the control panel other than enabling logging & Proxy setting.
> Attaching error log files here.
> Also tried to open the jnlp file from IE11 & also downloaded the file to C:\temp. Same behavior.
> Path to jnlp tried : https://docs.oracle.com/javase/tutorialJWS/samples/uiswing/AccessibleScrollDemoProject/AccessibleScrollDemo.jnlp
> Any pointers are most welcome. Somehow I feel that the proxy setting we provided is not applied and is reverting to DIRECT connection.
> JnlpLaunchErrorLogs_With_ProxyConfigScriptDefined.zip
> JnlpLaunchErrorLogs_With_ProxyServerHardcoded.zip

Another Observation:
If I keep clicking the "AccessibleScrollDemo.jnlp" in C:\temp folder, after few attempts the applications starts just fine. From the logs (attached), I can see that it is running from cache. So during the previous ailed attempts the associated files got downloaded to cache and then finally it started.
Not able to find out why it keeps failing in between though.
the proxy server details provided is valid and my system has internet connectivity using that.
Any suggestion as to how we can get a consistent successful application launch everytime?
log:

**Comment by VargheseJohnAllianz** [comment] 2019-08-01 14:05
[Working_Log_itw-javantx-2019-08-01_19_08_59.558.log.zip](https://github.com/AdoptOpenJDK/IcedTea-Web/files/3457087/Working_Log_itw-javantx-2019-08-01_19_08_59.558.log.zip)

**Comment by douph1** [comment] 2019-08-01 15:25
>Using the Rhino based PAC evaluator for url http://pacfile.allianz/insurance.pac
then
>Unable to use Firefox's proxy settings. Using "DIRECT" as proxy type.

seems strange to me

Your pac file seems not to be applied. ( don't know why and I don't have proxy/pac env to try )

Can you show us the log with "Manual proxy server" by settings the same things as present in the pac file ?
Also, is you computer be able to resolve public DNS (or this is just the proxy wich is allowed to ) ?

>No setting changed in the control panel other than enabling logging & Proxy setting.
After that you can try to enable debugging too in itweb-settings / Debugging (Maybee Rhino will show us something )

**Comment by VargheseJohnAllianz** [comment] 2019-08-01 15:29
log with manual proxy server (same proxy server is defined in PAC file) with debugging enabled: 
[JnlpLaunchErrorLogs_With_ProxyServerHardcoded.zip](https://github.com/AdoptOpenJDK/IcedTea-Web/files/3457471/JnlpLaunchErrorLogs_With_ProxyServerHardcoded.zip)

Only Proxy is allowed to resolve public DNS

**Comment by douph1** [comment] 2019-08-01 16:45
can you confirm that you have only itw 1.8.2 in the path ? `javaws -version`
must show
`icedtea-web 1.8.2`

**Comment by VargheseJohnAllianz** [comment] 2019-08-02 05:42
> can you confirm that you have only itw 1.8.2 in the path ? javaws -version
> must show
> icedtea-web 1.8.2

Log attached: Version looks good, icedtea-web 1.8.2 is displayed.

[javaws_version.zip](https://github.com/AdoptOpenJDK/IcedTea-Web/files/3459745/javaws_version.zip)


> In the log from 19h08 the proxy seems to be applied.
> Is this run as worked ?

Nope, with the proxy server hardcoded, the behaviour is as below:
"
If I keep clicking the "AccessibleScrollDemo.jnlp" in C:\temp folder, on 3rd attempt the applications starts just fine. From the logs (attached), I can see that it is running from cache. So during the previous 2 failed attempts the associated files (jnlp file in first attempt, jar file in second attempt) got downloaded to cache and then finally application started on third attempt.
"
I am checking if I can reproduce the same with Proxy Config script path instead of Server.
But really strange behaviour.. :(

Thanks,

**Comment by VargheseJohnAllianz** [comment] 2019-08-02 13:21
I can confirm this behavior with Proxy Config Script also. On third attempt, the application launches fine.
Any pointers for this behavior?

**Comment by VargheseJohnAllianz** [comment] 2019-08-02 13:29
Also on a related note, is it possible to configure IceTea-Web to read Proxy setting from Internet Settings in Windows registry?

Thanks,

**Comment by JAIMY86** [comment] 2019-08-05 12:07
Dear Team, 

Friendly Reminder!

Any updates from your end after analyzing the logs.

**Comment by judovana** [comment] 2019-08-22 18:14
> Dear Team,
> 
> Friendly Reminder!
> 
> Any updates from your end after analyzing the logs.

Hi! Itw had always nearly no support on windows, because I do not know ITW developer with windows. Not even with only access   to windows. Unless you persuade Karakun guys to fix it for you, we will need your help.   If you are bale to debug any generic java app, you can debug also ITW. There is no magic. it is  main class on classpath like anything else.   Sorry for bad news, but  withhout yor help, we will not be able tu help you.

**Comment by JAIMY86** [comment] 2019-11-21 12:25
> Dear Team,
> Friendly Reminder!
> Any updates from your end after analyzing the logs.
> 
> Hi! Itw had always nearly no support on windows, because I do not know ITW developer with windows. Not even with only access   to windows. Unless you persuade Karakun guys to fix it for you, we will need your help.   If you are bale to debug any generic java app, you can debug also ITW. There is no magic. it is  main class on classpath like anything else.   Sorry for bad news, but  withhout yor help, we will not be able tu help you.

Hello Team,

Is there any update on the bug?

We tried with latest AdoptOpenJDK JRE 8u232, but still the bug is present.

Kindly support/provide a possible timeline on the bug fix as its seems to be a major show stopper for our JRE migration for Win10 on enterprise level.

**Comment by KarstenL680** [comment] 2020-05-21 12:31
Hello Team,

it is now more than half a year and the bug is still present, do you have any updates on this?

Regards

**Comment by sclassen** [comment] 2020-05-21 20:08
We are still working on v 2.0
Until then you can have a look at openwebstart.com
It is based on the the v 2.0 alpha releases of ITW

**Comment by hendrikebbers** [comment] 2020-05-22 11:25
More details: 
For me it looks like that this is related to the proxy handling of ITW.

The tool OpenWebStart (openwebstart.com) is based on ITW. In OpenWebStart we replaced the proxy handling of ITW with a new implementation since we found several problems in the proxy handling of ITW. We have not done this change directly in ITW since we wanted to test the new implementation first without "destroying" proxy functionality in ITW. Since the proxy handling in OpenWebStarts looks really good I hope that we can migrate the new code in some future to ITW. @KarstenL680 you could help us by trying your application with OpenWebStart. Let us please now if the behaviour is the same or if the error does not happen with the new proxy handling.

**Comment by JAIMY86** [comment] 2020-05-22 11:37
@hendrikebbers , with Openwebstart, issue seems to be not appearing while running JNLP files directly from internet and also the proxy settings are taking from the default browser settings.

**Comment by hendrikebbers** [comment] 2020-05-22 13:39
Very good :)
We plan to do  the migration in near future. Once this is done a new version of ITW will be released.

**Closed** 2020-09-21 12:06 UTC
Labels: bug
