### ISSUE TITLE
Receiving error: Warning - your JRE - 11.0.2 - does not match requested JRE - 1.6

### ISSUE THREAD

**Issue by karlgee** [AdoptOpenJDK/IcedTea-Web#205] opened 2019-04-26 00:30 UTC
After an update on Ubuntu 18.04 in mid April of 2019 icedtea stopped working.  We get this error in /var/log syslog:
Apr 25 17:25:00 host org.gnome.Shell.desktop[1685]: Warning - your JRE - 11.0.2 - does not match requested JRE - 1.6
Apr 25 17:25:00 host org.gnome.Shell.desktop[1685]: Warning - your JRE - 11.0.2 - does not match requested JRE - 1.6
Apr 25 17:25:00 host user: IcedTea-Web java error - for more info see itweb-settings debug options or console. See http://icedtea.classpath.org/wiki/IcedTea-Web#Filing_bugs for help.
Apr 25 17:25:00 host user: IcedTea-Web java error manual log:
Apr 25 17:25:00 host user: Warning - your JRE - 11.0.2 - does not match requested JRE - 1.6
Apr 25 17:25:00 host org.gnome.Shell.desktop[1685]: Warning - your JRE - 11.0.2 - does not match requested JRE - 1.6
Apr 25 17:25:00 host org.gnome.Shell.desktop[1685]: Warning - your JRE - 11.0.2 - does not match requested JRE - 1.6
Apr 25 17:25:00 host user: IcedTea-Web java error - for more info see itweb-settings debug options or console. See http://icedtea.classpath.org/wiki/IcedTea-Web#Filing_bugs for help.
Apr 25 17:25:00 host user: IcedTea-Web java error manual log:
Apr 25 17:25:00 host user: Warning - your JRE - 11.0.2 - does not match requested JRE - 1.6
Apr 25 17:25:00 host org.gnome.Shell.desktop[1685]: selected jre: /usr/lib/jvm/default-java
Apr 25 17:25:00 host org.gnome.Shell.desktop[1685]: Unrecognized option: -Xincgc
Apr 25 17:25:00 host org.gnome.Shell.desktop[1685]: Error: Could not create the Java Virtual Machine.
Apr 25 17:25:00 host org.gnome.Shell.desktop[1685]: Error: A fatal exception has occurred. Program will exit.

We have been using icedtea with an online schooling at home program "https://peak.getfueled.com".  It has a java program called "blackboard collaborator".  Icedtea has worked fine with Ubuntu 16.04 and it was confirmed working with 18.04, but as of the icedtea patch included in mid April it has not worked.

**Comment by douph1** [comment] 2019-04-26 06:35
It seems that ubuntu as ugraded icedtea-web on 15 Mar 2019 icedtea-web is upgraded to (**1.8**-0ubuntu8~18.04) for bionic (18.04)

http://changelogs.ubuntu.com/changelogs/pool/universe/i/icedtea-web/icedtea-web_1.8-0ubuntu8~18.04/changelog

and on 26 Mar 2019 openjdk-11-jdk package move from java 10.0.2 to java 11.0.2 **11.0.2**+9-3ubuntu1~18.04.3) bionic-security 

http://changelogs.ubuntu.com/changelogs/pool/main/o/openjdk-lts/openjdk-lts_11.0.2+9-3ubuntu1~18.04.3/changelog

**Comment by douph1** [comment] 2019-04-26 06:39
@karlgee can you share the JNLP from "blackboard collaborator" ?
or at minimum the xml tag "java (or j2se)" in the jnlp

**Comment by karlgee** [comment] 2019-04-26 14:48
I can.  See attached.

Thank you

**Comment by douph1** [comment] 2019-04-26 14:50
reply by mail seems not add attachment to github

**Comment by karlgee** [comment] 2019-04-26 15:36
[meeting.zip](https://github.com/AdoptOpenJDK/icedtea-web/files/3121951/meeting.zip)

Okay, inside the meeting.zip file is a file named meeting.jnlp.  This is the file Blackboard Collaborator uses.

**Comment by douph1** [comment] 2019-04-26 18:54
The jnlp is not very well written (hint : use https://github.com/AlBundy33/JaNeLa )
* `<version>12.6</version>` must not be placed insde `<information>`
* `<resources os="Mac\ OS\ X">` protect space .. I think it's not required and dont match


And as you see in your output ( last 3 line ) and mine,
the least and major problem is the error 

javaws meeting.jnlp 
```
selected jre: /usr/lib/jvm/default-java
WARNING: package javax.jnlp not in java.desktop
Warning - your JRE - 11.0.2 - does not match requested JRE - 1.6
Warning - your JRE - 11.0.2 - does not match requested JRE - 1.6
Warning - your JRE - 11.0.2 - does not match requested JRE - 1.6
Warning - your JRE - 11.0.2 - does not match requested JRE - 1.6
selected jre: /usr/lib/jvm/default-java
Unrecognized option: -Xincgc
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.

```
**Unrecognized option: -Xincgc**
"-Xincgc "  -Xincgc has been removed since java 9

The issue is the jnlp file.
Ask your provider https://peak.getfueled.com to remove -Xincgc option

Issue can be closed

**Comment by karlgee** [comment] 2019-04-26 21:40
Okay, I'll write them and let them know.  Thank you very much for getting back to me so soon, and looking at this!

**Comment by sclassen** [comment] 2019-05-14 21:43
closing this issue for now.
Please reopen if there is an updated JNLP which still causes the error

**Closed by sclassen** 2019-05-14 21:43 UTC
Labels: Waiting on OP, bug, question
