### ISSUE TITLE
Just a question about maven build and test cases

### ISSUE THREAD

**Issue by vnashkev** [AdoptOpenJDK/IcedTea-Web#750] opened 2021-02-12 12:07 UTC
Hallo,
maven build for [tags/icedtea-web-2.0.0-alpha18] fails because of unit tests.

OS - Windows 10
Oracle jdk 1.8.0_121

Is it a known problem or i did something wrong?

Thank you in advance, 
Vitali

**Comment by sclassen** [comment] 2021-02-12 14:23
No we are not aware of this.
We have a CI set up for both Win and Linux which runs any commit on master and it has not detected the failure.
Can you give us the list of tests which fail so we can try to reproduce this, thanks

**Comment by vnashkev** [comment] 2021-02-12 18:12
First of all i slightly modified pom.xml for integration module to run tests sequentially.
Without that result is the same but it is much more difficult to read.
If necessary i can repeat it whithout changes.
For results please see attachment. 

```
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <configuration>
<!--
                    <forkCount>1.0C</forkCount>
                    <reuseForks>false</reuseForks>
-->
                    <!-- limiting memory for travis which uses docker to run builds -->
                    <!-- if memory is not limited the forked JVMs use too much memory and are killed by the OS -->
                    <argLine>-Xmx1024m -XX:MaxPermSize=256m</argLine>
                </configuration>
            </plugin>

```
[protocol-icedtea-web1.txt](https://github.com/AdoptOpenJDK/IcedTea-Web/files/5973589/protocol-icedtea-web1.txt)

**Comment by sclassen** [comment] 2021-02-12 21:14
The error is very confusing...
Are you able to run other tags in your setup successfully or are all tags failing for you?

**Comment by vnashkev** [comment] 2021-02-13 11:04
What do you mean with "other tag"?
I can build openwebstart with tests. I can build icedtea-web without tests.
I have tried icedtea-web on 2 windows PCs (both Windows 10 & jdk 1.8). Tests failed on both. 

On ubuntu 20.04 with jdk 1.8 icedtea-web build succeeded with tests.

**Comment by sclassen** [comment] 2021-02-13 13:03
I mean git tags of ITW such as alpha 12 or others.
The reason I ask is to find out if the issue has been introduced recently or not

**Comment by vnashkev** [comment] 2021-02-13 13:56
Just tried alpha17 & alpha15. Both fail.

**Comment by vnashkev** [comment] 2021-02-13 14:43
I found a reason in integration/pom.xml :
```
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <configuration>
                    <forkCount>1.0C</forkCount>
                    <reuseForks>false</reuseForks>
                    <!-- limiting memory for travis which uses docker to run builds -->
                    <!-- if memory is not limited the forked JVMs use too much memory and are killed by the OS -->
                    <argLine>-Xmx1024m -XX:MaxPermSize=256m</argLine>
                </configuration>
            </plugin>
```
If i replace it with 
```
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <configuration>
                        <forkMode>always</forkMode>
                </configuration>
            </plugin>
```
everything is GREEN.

Generally speaking if each and every test runs in its own JVM then everything is Ok.
If 2 or more tests share the same JVM it may fail because of static nature of JNLPRuntime class.
Just look what happens if within the same JVM the following calls will be made :

```
JNLPRuntime.setHeadless(...);
JNLPRuntime.initialize();
JNLPRuntime.setHeadless(...);
```
This exactly the case if `MissingCodebases1Test` and `MissingCodebases3Test` tests share the same JVM.

**Comment by sclassen** [comment] 2021-02-13 16:24
So the issue is with maven or one of its plugins. Since the checked in config is runing on the CI windows infrastructure.
What version of maven do you use?

**Comment by vnashkev** [comment] 2021-02-13 19:33
I use maven 3.6.3

**Comment by sclassen** [comment] 2021-02-13 21:10
OK, I updated our CI Server from 3.5.4 to 3.6.3 but still all the tests are green.
Also all the plugin versions are fixed and thus should be the same.
I am puzzled why the build behaves differently on your Windows then on ours.

**Comment by SchwingSK** [comment] 2021-02-24 15:22
The order must be different on your JVMs, and the order in your CI server is just 'lucky'. By changing the order in which tests are executed, I can reproduce a failure every time:

    [ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 4.09 s <<< FAILURE! - in net.adoptopenjdk.icedteaweb.integration.reproducers.extensionresources.ManagedApplicationWithExtensionResourceStartedTest

The order i use:

            <configuration>
                <forkCount>1.0C</forkCount>
                <reuseForks>false</reuseForks>
                
                
                <argLine>-Xmx1024m -XX:MaxPermSize=256m</argLine>
                <runOrder>reversealphabetical</runOrder>
            </configuration>

By using 'alphabetical' tests never seem to fail.
Hope this helps.

**Comment by sclassen** [comment] 2021-02-25 10:41
The best you can do is create a branch where the issue is reproduceable and open a PR for this branch.
Once we can also reproduce the issue we will let you know and then you can propose a fix on the same branch.

**Closed** 2021-05-27 08:16 UTC
