### ISSUE TITLE
java.io.FileNotFoundException: C:\Users\mmuthu2\.cache\icedtea-web\cache\recently_used.cache (Access is denied)

### ISSUE THREAD

**Issue by MMuthu4322** [AdoptOpenJDK/IcedTea-Web#944] opened 2024-05-31 12:22 UTC
I was using OpenWebstart without issues in Windows 10, I have upgraded to Windows 11 and the product no longer works. 

There is no \.cache\icedtea-web\cache folder. Please see the logs attached. 
Kindly assist on this.

I can see the below file, but I am not able to open it.

C:\Users\mmuthu2\.cache\icedtea-web\cache\recently_used.cache

[2024-05-31_17_49_59.692-ows-stage1.log](https://github.com/user-attachments/files/15513516/2024-05-31_17_49_59.692-ows-stage1.log)
[2024-05-31_17_49_59.692-ows-stage2.log](https://github.com/user-attachments/files/15513517/2024-05-31_17_49_59.692-ows-stage2.log)

**Comment by sclassen** [comment] 2024-06-07 21:56
duplicate of https://github.com/karakun/OpenWebStart/issues/585

**Closed by sclassen** 2024-06-07 21:56 UTC
