### ISSUE TITLE
Auto registration with JNLP and JAR not working

### ISSUE THREAD

**Issue by karianna** [AdoptOpenJDK/IcedTea-Web#268] opened 2019-05-28 12:25 UTC
Hello
I'm installed JRE (OpenJDK8U-jre_x64_windows_hotspot_8u212b03.msi) and (1.8 itw-installer.msi) but it doesn't work like Oracle JRE. 
The applications that has executable files, it looks works fine, but I'm talking about (.jnlp and .jar files).
Is not possible to only do a double click to open.
There is some tip to make work like Oracle JRE?

_Originally posted by @wanderleihuttel in https://github.com/AdoptOpenJDK/openjdk-installer/issues/22#issuecomment-495995559_

**Comment by douph1** [comment] 2019-05-28 12:28
@wanderleihuttel can you try with 1.8.1 from here ?
https://adoptopenjdk.net/icedtea-web.html

**Comment by wanderleihuttel** [comment] 2019-05-28 20:20
Hello @karianna ! 
I've tried with this version and not worked.

I've installed the version "OpenJDK8U-jre_x64_windows_hotspot_8u212b03.msi":

````
# Java is recognized in the PATH variable
PS C:\Users\wanderlei\Desktop> java -version
openjdk version "1.8.0_212"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_212-b03)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.212-b03, mixed mode)
````

````
# Windows regedit entries
Windows Registry Editor Version 5.00
[HKEY_CLASSES_ROOT\.jar]
@="AdoptOpenJDK.jarfile"
"Content Type"="application/jar"
[HKEY_CLASSES_ROOT\AdoptOpenJDK.jarfile]
[HKEY_CLASSES_ROOT\AdoptOpenJDK.jarfile\shell]
[HKEY_CLASSES_ROOT\AdoptOpenJDK.jarfile\shell\open]
[HKEY_CLASSES_ROOT\AdoptOpenJDK.jarfile\shell\open\command]
@="\"C:\\Program Files\\AdoptOpenJDK\\jre-8.0.212.03-hotspot\\bin\\javaw.exe\" -jar \"%1\" %*"
````

I've tried to run this application (in cmd "javaw.exe -jar ofx2csv 1.0.jar") and with mouse double clicking and no one way worked! I don't know why!
The site of application:
https://tudoexcel.wordpress.com/category/ofx/
Direct download
https://drive.google.com/uc?export=download&id=18piAgPEtDPktTTCgQ8mR8spii7TAv0SX

After install "icedtea-web-1.8.1.msi" the following registry entries was created and if I've try to execute a JNLP using cmd or by mouse double clicking, the application worked fine

````
Windows Registry Editor Version 5.00

[HKEY_CLASSES_ROOT\.jnlp]
@="JNLPFile"
"Content Type"="application/x-java-jnlp-file"
[HKEY_CLASSES_ROOT\JNLPFile]
@="JNLP File"
"EditFlags"=dword:00010000
[HKEY_CLASSES_ROOT\JNLPFile\DefaultIcon]
@="C:\\Program Files\\IcedTeaWeb\\WebStart\\share\\pixmaps\\javaws.ico"
[HKEY_CLASSES_ROOT\JNLPFile\shell]
[HKEY_CLASSES_ROOT\JNLPFile\shell\open]
[HKEY_CLASSES_ROOT\JNLPFile\shell\open\command]
@="\"C:\\Program Files\\IcedTeaWeb\\WebStart\\bin\\javaws.exe\" \"%1\""
[HKEY_CLASSES_ROOT\jnlp]
@="URL:jnlp Protocol"
"URL Protocol"=""
[HKEY_CLASSES_ROOT\jnlp\shell]
[HKEY_CLASSES_ROOT\jnlp\shell\open]
[HKEY_CLASSES_ROOT\jnlp\shell\open\command]
@="\"C:\\Program Files\\IcedTeaWeb\\WebStart\\bin\\javaws.exe\" \"%1\""
[HKEY_CLASSES_ROOT\jnlps]
@="URL:jnlp Protocol"
"URL Protocol"=""
[HKEY_CLASSES_ROOT\jnlps\shell]
[HKEY_CLASSES_ROOT\jnlps\shell\open]
[HKEY_CLASSES_ROOT\jnlps\shell\open\command]
@="\"C:\\Program Files\\IcedTeaWeb\\WebStart\\bin\\javaws.exe\" \"%1\""
````
But this specific application JNLP doesn't run:
http://emissores.sebrae.com.br/nfe/v401/producao/emissorNFe-4_0_1.jnlp

Is necessary to run with the flag "-allowredirect".

If I install "java-1.8.0-openjdk-1.8.0.201-1.b09.ojdkbuild.windows.x86_64.msi" (https://github.com/ojdkbuild/ojdkbuild) the jar and jnlp files are running fine with mouse double click, with exception of jnlp that I've mentioned above, that is necessary to run using the flag "-allowredirect".

**Comment by douph1** [comment] 2019-05-28 20:47
"javaw.exe -jar ofx2csv 1.0.jar"
can't work because of space in jar name

You are showing us HKEY_CLASSES_ROOT

>HKEY_CLASSES_ROOT hive is actually combined data found in both the HKEY_LOCAL_MACHINE hive (HKEY_LOCAL_MACHINE\Software\Classes) and the HKEY_CURRENT_USER hive (HKEY_CURRENT_USER\Software\Classes)

Can you export both HKLM and HKCU ?

Can you compare the reg key created by ojkdbuild ?

**Comment by wanderleihuttel** [comment] 2019-05-29 14:30
Hello @douph1!

About run the this specific jar file, even renaming the file or using quotes, is not working with AdoptOpenJDK, only works with ojkdbuild.

About registry keys, I've uninstall java and removed manually all registry keys entries about (.jar and .jnlp files), and then I installed AdoptOpenJDK and exported the keys from registry and made the tests.
The .jar file doesn't open, even using cmd.

I've did the same using ojkdbuild, and .jar and .jnlp files worked fine, with exception of this (http://emissores.sebrae.com.br/nfe/v401/producao/emissorNFe-4_0_1.jnlp), that is necessary to execute with flag "-allowredirect".

Following the link to download all of registry entries from (AdoptOpenJDK and ojkdbuild)
https://we.tl/t-F0YWYaNLjy

**Comment by douph1** [comment] 2019-05-29 15:12
>even using cmd

so this as nothing linked to your title "registration JNLP and JAR"

It seems the jnlp is not well delivered :
JaNeLA (hint : use https://github.com/AlBundy33/JaNeLa)  complain because of the first emtpy line.
The first line must be a xml tag ( not a empty line )

then other errors shown by JaNeLA

ignoring this, I finally also got a exception from javaws 1.8

`net.sourceforge.jnlp.LaunchException: Fatal: Read Error: Could not read or parse the JNLP file. You can try to download this file manually and send it as bug report to IcedTea-Web team.
	at net.sourceforge.jnlp.Launcher.fromUrl(Launcher.java:489)
	at net.sourceforge.jnlp.Launcher.launch(Launcher.java:289)
	at net.sourceforge.jnlp.runtime.JnlpBoot.run(JnlpBoot.java:67)
	at net.sourceforge.jnlp.runtime.Boot.run(Boot.java:270)
	at net.sourceforge.jnlp.runtime.Boot.run(Boot.java:63)
	at java.security.AccessController.doPrivileged(Native Method)
	at net.sourceforge.jnlp.runtime.Boot.main(Boot.java:210)
Caused by: java.io.IOException: java.lang.NullPointerException: name can't be null
	at net.sourceforge.jnlp.JNLPFile.openURL(JNLPFile.java:318)
	at net.sourceforge.jnlp.JNLPFile.<init>(JNLPFile.java:240)
	at net.sourceforge.jnlp.JNLPFile.<init>(JNLPFile.java:215)
	at net.sourceforge.jnlp.JNLPFile.<init>(JNLPFile.java:200)
	at net.sourceforge.jnlp.JNLPFile.<init>(JNLPFile.java:186)
	at net.sourceforge.jnlp.Launcher.fromUrl(Launcher.java:453)
	... 6 more
Caused by: java.lang.NullPointerException: name can't be null
	at java.io.FilePermission.init(FilePermission.java:191)
	at java.io.FilePermission.<init>(FilePermission.java:277)
	at java.lang.SecurityManager.checkRead(SecurityManager.java:888)
	at java.io.FileInputStream.<init>(FileInputStream.java:127)
	at net.sourceforge.jnlp.JNLPFile.openURL(JNLPFile.java:316)
	... 11 more`

Can you confirm a error message ? An exception ? the same as above ?

I bypass this error by changing codebase to "." after downloading the jnlp and jars.. so I think the first empty line is *the first problem*.

Also it seems the jar AND the Jnlp are signed.

We can't fix the jnlp to test .. without invalidate signature.

Can you try another jnlp (unsigned) sample from oracle ?

Is someone have another signed Jnlp url to confirm a problem with signed jnlp ?
(Signed jnlp : JNLP-INF/APPLICATION.JNLP must be included in a jar ) ..

**Comment by douph1** [comment] 2019-05-29 15:14
>only works with ojkdbuild

ojdkbuild use IcedTea-Web 1.7 branch

Maybee a regression, can you test your signed jnlp with 1.7.2 and AdoptOpenJdk to confirm maybe a regression between 1.7.2 and 1.8
http://icedtea.wildebeest.org/download/icedtea-web-binaries/1.7.2/windows/itw-installer.msi

**Comment by wanderleihuttel** [comment] 2019-05-29 16:23
Hello @douph1! 
About removing the empty line in the .JNLP file, I've received the same error that you've got it.
````
net.sourceforge.jnlp.LaunchException: Fatal: Read Error: Could not read or parse the JNLP file. You can try to download this file manually and send it as bug report to IcedTea-Web team.
	at net.sourceforge.jnlp.Launcher.fromUrl(Launcher.java:489)
	at net.sourceforge.jnlp.Launcher.launch(Launcher.java:289)
	at net.sourceforge.jnlp.runtime.JnlpBoot.run(JnlpBoot.java:67)
	at net.sourceforge.jnlp.runtime.Boot.run(Boot.java:270)
	at net.sourceforge.jnlp.runtime.Boot.run(Boot.java:63)
	at java.security.AccessController.doPrivileged(Native Method)
	at net.sourceforge.jnlp.runtime.Boot.main(Boot.java:210)
Caused by: java.io.IOException: java.lang.NullPointerException: name can't be null
	at net.sourceforge.jnlp.JNLPFile.openURL(JNLPFile.java:318)
	at net.sourceforge.jnlp.JNLPFile.<init>(JNLPFile.java:240)
	at net.sourceforge.jnlp.JNLPFile.<init>(JNLPFile.java:215)
	at net.sourceforge.jnlp.JNLPFile.<init>(JNLPFile.java:200)
	at net.sourceforge.jnlp.JNLPFile.<init>(JNLPFile.java:186)
	at net.sourceforge.jnlp.Launcher.fromUrl(Launcher.java:453)
	... 6 more
Caused by: java.lang.NullPointerException: name can't be null
	at java.io.FilePermission.init(FilePermission.java:191)
	at java.io.FilePermission.<init>(FilePermission.java:277)
	at java.lang.SecurityManager.checkRead(SecurityManager.java:888)
	at java.io.FileInputStream.<init>(FileInputStream.java:127)
	at net.sourceforge.jnlp.JNLPFile.openURL(JNLPFile.java:316)
	... 11 more
````

> We can't fix the jnlp to test .. without invalidate signature.
> Can you try another jnlp (unsigned) sample from oracle ?
> 
Sorry, but I'm only an end user. I have just more one .JNLP for testing, but I don't know if attend your requisites
Is possible to get from the link below:
https://solucaodigital.acsoluti.com.br/site/emitircertificado
https://emissor.ca.inf.br/prod/Emissor.jnlp


> Maybee a regression, can you test your signed jnlp with 1.7.2 and AdoptOpenJdk to confirm maybe a regression between 1.7.2 and 1.8
> http://icedtea.wildebeest.org/download/icedtea-web-binaries/1.7.2/windows/itw-installer.msi
I've testes with 1.7.2 and the same exception occurs

````
net.sourceforge.jnlp.LaunchException: Fatal: Read Error: Could not read or parse the JNLP file. You can try to download this file manually and send it as bug report to IcedTea-Web team.
	at net.sourceforge.jnlp.Launcher.fromUrl(Launcher.java:489)
	at net.sourceforge.jnlp.Launcher.launch(Launcher.java:289)
	at net.sourceforge.jnlp.runtime.JnlpBoot.run(JnlpBoot.java:67)
	at net.sourceforge.jnlp.runtime.Boot.run(Boot.java:270)
	at net.sourceforge.jnlp.runtime.Boot.run(Boot.java:63)
	at java.security.AccessController.doPrivileged(Native Method)
	at net.sourceforge.jnlp.runtime.Boot.main(Boot.java:210)
Caused by: java.io.IOException: java.lang.NullPointerException: name can't be null
	at net.sourceforge.jnlp.JNLPFile.openURL(JNLPFile.java:318)
	at net.sourceforge.jnlp.JNLPFile.<init>(JNLPFile.java:240)
	at net.sourceforge.jnlp.JNLPFile.<init>(JNLPFile.java:215)
	at net.sourceforge.jnlp.JNLPFile.<init>(JNLPFile.java:200)
	at net.sourceforge.jnlp.JNLPFile.<init>(JNLPFile.java:186)
	at net.sourceforge.jnlp.Launcher.fromUrl(Launcher.java:453)
	... 6 more
Caused by: java.lang.NullPointerException: name can't be null
	at java.io.FilePermission.init(FilePermission.java:191)
	at java.io.FilePermission.<init>(FilePermission.java:277)
	at java.lang.SecurityManager.checkRead(SecurityManager.java:888)
	at java.io.FileInputStream.<init>(FileInputStream.java:127)
	at net.sourceforge.jnlp.JNLPFile.openURL(JNLPFile.java:316)
	... 11 more
````

**Comment by sclassen** [comment] 2019-05-31 09:15
I debugged a little into the JNLP. It looks like the problem is not in the file rather in the server config.
I see the following line in the log:
 ```
The resource https://emissores.sebrae.com.br/nfe/v401/producao/emissorNFe-4_0_1.jnlp is being redirected (302) to http://conteudo.sebrae.com.br/nfe/v401/producao/emissorNFe-4_0_1.jnlp. This is disabled by default. If you wont to allow it, run javaws with -allowredirect parameter.
```
You can easily verify the redirect with a browser or other tools.

The following URL does not do the redirect and works fine:
```
https://emissor.ca.inf.br/prod/Emissor.jnlp
```

**Comment by Jamila891** [comment] 2020-09-16 08:24
Hi @douph1, can we close this issue?

**Comment by douph1** [comment] 2020-09-17 07:30
@wanderleihuttel can you give more precise info
and if always the case split this issue in two or three new  issues .. 
One for the jnlp and one or thow for the jar file

>I've tried to run this application (in cmd "javaw.exe -jar ofx2csv 1.0.jar") and with mouse double clicking and no one way worked!

Neither javaw.exe in cmd neither via double click seems two unrelated problems

>but I'm talking about (.jnlp and .jar files).
>Is not possible to only do a double click to open.

Double click on which one ? jar or jnlp ?

**Comment by wanderleihuttel** [comment] 2020-09-17 22:02
Hello @douph1 !
Sorry for this long delay!
Here in Brazil a lot of systems is using a jar file to sign files (using digital certificates), and using Oracle Java I just double click in file and it works, but when I've tried to use OpenJDK it doesn't worked.

Unfortnately I didn't tried anymore because the coworkers couldn't wait and then I'm using and old version on Java Oracle.
When I will not be so busy I will try to try again.

Best regards and thanks for your time

**Comment by castuloramirez** [comment] 2021-01-13 14:17
I works perfectly with AdoptOpenJDK 8  and the IcedTea-Web 1.8.3

![image](https://user-images.githubusercontent.com/27036721/104463697-63b0c180-55b2-11eb-94e4-d5dbd9961415.png)

**Closed** 2021-01-18 10:38 UTC
Labels: Waiting on OP, bug
